### ISSUE TITLE
bug  dataset_config

### ISSUE THREAD

**Issue by jayzhoukobe** [YushenLi807/WWW24-RAT#1]
params = load_config(args['config'], experiment_id)这行代码跳进函数后路径不对，导致加载不出来dataset_config

**Comment by YushenLi807** [comment]
这是一条示范运行命令
python run_expid.py --config ./configs/RAT_m2/movielenslatest_x1 --expid RAT_m2_movielenslatest_x1_10fold_retrieval --gpu 0
请注意--config后的地址要对应你项目文件地址，--expid后的模型配置名字需要在model_config.yaml里存在

**Comment by YushenLi807** [comment]
> params = load_config(args['config'], experiment_id)这行代码跳进函数后路径不对，导致加载不出来dataset_config

这是一条示范运行命令
python run_expid.py --config ./configs/RAT_m2/movielenslatest_x1 --expid RAT_m2_movielenslatest_x1_10fold_retrieval --gpu 0
请注意--config后的地址要对应你项目文件地址，--expid后的模型配置名字需要在model_config.yaml里存在

**Comment by jayzhoukobe** [comment]
感谢回复
在utils.py中 
dataset_configs = glob.glob(os.path.join(config_dir, 'dataset_config.yaml'))            bug
文件夹中不存在任何以'dataset_config.yaml'名字结尾的文件啊

**Comment by YushenLi807** [comment]
> 感谢回复 在utils.py中 dataset_configs = glob.glob(os.path.join(config_dir, 'dataset_config.yaml')) bug 文件夹中不存在任何以'dataset_config.yaml'名字结尾的文件啊

解决方法：
我们以movielenslatest为例，请将项目文件地址为WWW24-RAT/configs/datasets/movielenslatest_x1.yaml文件以软链接或者复制（使用复制要注意两边文件信息的同步）的形式放入WWW24-RAT/configs/RAT_m2/movielenslatest_x1/dataset_config.yaml，（将movielenslatest_x1.yaml改名为dataset_config.yaml）
问题产生原因：
因为我为了dataset和RAT_m2配置文件信息的同步，所以使用了软链接，在github上传的时候，会把软链接吃掉，导致我软链接的dataset_config.yaml文件缺失。

**Comment by jayzhoukobe** [comment]
感谢大佬回答，谢谢！

**Comment by YushenLi807** [comment]
> 感谢大佬回答，谢谢！

没关系～不是大佬:)
